name: qris_safe_v1
description: "Cek keamanan link"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  qr_code_scanner:
    git:
      url: https://github.com/asmrtfm/qr_code_scanner
      ref: patch-1
      version: ^1.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true
